name: Deploy to AWS

on:
  push:
    branches:
      - develop
      - staging
      - production
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION || 'ap-northeast-1' }}

    - name: Set up environment
      run: |
        echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" >> .env
        echo "AWS_REGION=${{ secrets.AWS_REGION || 'ap-northeast-1' }}" >> .env

    - name: CDK Bootstrap (if needed)
      run: |
        npx cdk bootstrap || echo "Bootstrap already exists"

    - name: Deploy to dev (develop branch)
      if: github.ref == 'refs/heads/develop'
      run: npm run deploy:dev -- --require-approval never

    - name: Deploy to staging (staging branch)
      if: github.ref == 'refs/heads/staging'
      run: npm run deploy:staging -- --require-approval never

    - name: Deploy to prod (production branch)
      if: github.ref == 'refs/heads/production'
      run: npm run deploy:prod -- --require-approval never

    - name: Show outputs
      run: |
        echo "Deployment completed!"
        echo "Check AWS CloudFormation console for stack outputs"